### ISSUE TITLE
Request Logging

### ISSUE THREAD

**Issue by az-iar** [katsana/minions-server#3]
I am trying to figure out how to log incoming request. I can see that there is a `LogRequest` middleware. But not sure where it is being log into. 

Also when running the `minions:serve` there is no output, as compared to [laravel-websocket](https://github.com/beyondcode/laravel-websockets), which make it easier to check if it is actually running and receiving request.

**Comment by crynobone** [comment]
All logs are push to `stdout`, so you can do the following:

```
php artisan minions:serve > /path/to/minions.log
```

Supervisor can handle this automatically:

```ini
[program:minions]
command=php artisan minions:serve
directory=/var/www/project/current
stdout_logfile=/var/www/project/storage/logs/minions.log
stderr_logfile=/var/www/project/storage/logs/minions_err.log
stdout_logfile_maxbytes=50MB
stderr_logfile_backups=10
autostart=true
autorestart=true
```

**Comment by az-iar** [comment]
Thanks @crynobone
